#+title: Cretaceous Constraints Algorithm
#+author: Ilja J. Kocken and Richard E. Zeebe
#+date: 2024-09-30

This R code contains the algorithm to match data to an astronomical solution, and is part of the work-in-progress publication titled: "A Revised Astronomically Tuned Time Scale for the Latest Cretaceous (Maastrichtian)".

* R package
This includes a simple R package with the following functions:

Some utility functions for spectral analysis and filtering, mostly wrapping around functions from [[https://cran.r-project.org/package=astrochron][~astrochron~]] [cite:@Meyers2014] that allow for a consistent interface.

- ~bandpass_filter()~: wrapper for ~astrochron::bandpass()~ that makes the output always the same format
- ~taner_filter()~: same as above but for ~astrochron::taner()~
- ~spectral_analysis()~: wrapper for ~astrochron::periodogram()~,
    ~astrochron::mtm()~, ~astrochron::mtmML96()~, ~astrochron::mtmPL()~,
    ~astrochron::lowspec()~ that unifies output
- ~plot_spectrum()~: make nice plots of the unified output from the above using [[https://cran.r-project.org/package=ggplot2][~ggplot2~]].
- nested versions of all of the above; filter multiple frequencies at once or do it grouped by some other variable.

These functions are specific to this study:
- ~construct_eccentricity()~: combines 405 and 100 kyr filters
- ~wrap_age_model()~: the algorithm that optimizes the match between data and solution; depends on the data, age model, solution, tiepoint uncertainty, proxy phase, target periods, frequency fraction (for filtering), filter options, age slider (by how much do we shift the record), kpg_age, and some more.

* Files Specific to the Manuscript
The file [[file:cretaceous_constraints.org]] contains all the working notes and plot creation code for this study. It is an [[https://orgmode.org/][org-mode]] file, best edited in [[https://www.gnu.org/software/emacs/][emacs]].

Within the large file some sections may be of particular interest:

- [[https://github.com/japhir/CretaceousConstraints/blob/main/cretaceous_constraints.org#table-of-final-age-model][table of final age model]]
- [[https://github.com/japhir/CretaceousConstraints/blob/main/cretaceous_constraints.org#a-wrap_age_model-for-all][wrap_age_model for all]]: where I set up simulation grids for the sensitivity analysis

* References
Meyers, S. R. (2014). astrochron: An R Package for Astrochronology. CRAN. http://cran.r-project.org/package=astrochron
